name: Docker Image Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v2
      with:
        username: ${{ secrets.SAMPLEAPP_ACR_USERNAME }}
        password: ${{ secrets.SAMPLEAPP_ACR_PASSWORD }}
        login-server: ${{ secrets.SAMPLEAPP_SERVER }}

    - uses: actions/checkout@v3

    - name: Build and Push Docker Image
      run: |
        docker build . --file WebApp.Dockerfile --tag ${{ secrets.SAMPLEAPP_SERVER }}/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER
        docker tag ${{ secrets.SAMPLEAPP_SERVER }}/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER ${{ secrets.SAMPLEAPP_SERVER }}/sample-app-aoai-chatgpt:latest
        docker push ${{ secrets.SAMPLEAPP_SERVER }}/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER
        docker push ${{ secrets.SAMPLEAPP_SERVER }}/sample-app-aoai-chatgpt:latest
