name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test_linux:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      # Step 4: Sanitize and Load Environment Variables
      - name: Load environment variables from .env
        run: |
          # Write secret to .env file and sanitize it
          echo "${{ secrets.ENV_FILE }}" > .env
          # Escape special characters and validate the file
          sed -i 's/"/\\"/g' .env
          if ! grep -qE '^[A-Za-z_][A-Za-z0-9_]*=' .env; then
            echo "Invalid .env format" >&2
            exit 1
          fi
          set -a
          . .env || true
          set +a

      # Step 5: Debug environment variables (Optional)
      - name: Debug environment variables
        run: |
          echo "Loaded environment variables:"
          cat .env

      # Step 6: Run tests with pytest
      - name: Test with pytest
        run: |
          export PYTHONPATH=$(pwd)
          coverage run -m pytest -v --show-capture=stdout
          coverage report -m --include=app.py,backend/*,tests/*
          coverage xml

      # Step 7: Generate Code Coverage Report
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '50 80'
